acc_types = \
    {
        '89': 'Wilful default',
        '93': 'Suit Filed(Wilful default )',
        '97': 'Suit Filed and Written- off',
        '32': 'Settled',
        '33': 'Post(WO) Settled',
        '34': 'Account Sold',
        '35': 'Written Off and Account Sold',
        '36': 'Account Purchased',
        '37': 'Account Purchased and Written Off',
        '38': 'Account Purchased and Settled',
        '39': 'Account Purchased and Restructured', '43': 'Written - off',
        '44': 'Settled',
        '45': 'Post(WO) Settled', '47': 'Written Off and Account Sold',
        '53': 'Suit Filed',
        '54': 'Suit Filed and Written - off',
        '55': 'Suit Filed and Settled',
        '56': 'Suit Filed and Post(WO) Settled',
        '57': 'Suit Filed and Account Sold',
        '58': 'Suit Filed and Written Off and Account Sold',
        '59': 'Suit Filed and Account Purchased',
        '60': 'Suit Filed and Account Purchased and Written Off',
        '61': 'Suit Filed and Account Purchased and Settled',
        '62': 'Suit Filed and Account Purchased and Restructured',
        '63': 'Suit Filed and Status Cleared',
        '64': 'Wilful Default and Restructured Loan',
        '65': 'Wilful Default and Restructured Loan(Govt.Mandated)',
        '66': 'Wilful Default and Settled',
        '67': 'Wilful Default and Post(WO) Settled',
        '68': 'Wilful Default and Account Sold',
        '69': 'Wilful Default and Written Off and Account Sold',
        '70': 'Wilful Default and Account Purchased',
        '72': 'Wilful Default and Account Purchased and Written Off',
        '73': 'Wilful Default and Account Purchased and Settled',
        '74': 'Wilful Default and Account Purchased and Restructured',
        '75': 'Wilful Default and Status Cleared',
        '76': 'Suit filed(Wilful default ) and Restructured',
        '77': 'Suit filed(Wilful default ) and Restructured Loan(Govt.Mandated)',
        '79': 'Suit filed(Wilful default ) and Settled',
        '81': 'Suit filed(Wilful default ) and Post(WO) Settled',
        '85': 'Suit filed(Wilful default ) and Account Sold',
        '86': 'Suit filed(Wilful default ) and Written Off and Account Sold',
        '87': 'Suit filed(Wilful default ) and Account Purchased',
        '88': 'Suit filed(Wilful default ) and Account Purchased and Written Off',
        '94': 'Suit filed(Wilful default ) and Account Purchased and Settled',
        '90': 'Suit filed(Wilful default ) and Account Purchased and Restructured',
        '91': 'Suit filed(Wilful default ) and Status Cleared',
        'loss':'rejected'


    }
